Algoritmo "EXE2"
//Elabore um algoritmo para calcular a media de um aluno. Para o calculo,
//o algoritmo deverá ler 3 notas. Mostre a media final.

Var
nota1:inteiro
nota2:inteiro
nota3:inteiro
media:real


Inicio
escreval("Informe sua 1º nota")
leia(nota1)

escreval("Informe sua 2º nota")
leia(nota2)

escreval("Informe sua 3º nota")
leia(nota3)

media:= (nota1+nota2+nota3)/ 3

escreval("Sua média foi:", media:2:1)


Fimalgoritmo